"""add diet allergy table

Revision ID: b180e2a9daa9
Revises: 17cbb706fa30
Create Date: 2025-11-27 15:59:56.484233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b180e2a9daa9'
down_revision: Union[str, Sequence[str], None] = '17cbb706fa30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_allergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diet', sa.String(length=50), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_allergy_id'), 'diet_allergy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diet_allergy_id'), table_name='diet_allergy')
    op.drop_table('diet_allergy')
    # ### end Alembic commands ###
